name: PR / Renovate

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow_ref }}
  cancel-in-progress: true

jobs:
  main:
    name: Validate
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Validate
        run: |
          npx --yes --package renovate -- renovate-config-validator